config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  resources :users
  resources :tweets

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', as: :signin             # Adding :as => :signin to the route gives us a signin_path helper to use in our views
  get '/signout' => 'sessions#destroy', as: :signout
  get '/auth/failure' => 'sessions#failure'

  post '/users/:id/go_back', to: 'users#go_back'

end

app/models/time_travel.rb
class Backward

	def reverse_time(hours)
  	timeline_search_results = []
  	hours_converted = hours * 60 * 60
    time = Time.now - hours_converted
    twitter.home_timeline(:count => 10).each do |tweet|
      if tweet.created_at > time
        timeline_search_results << [tweet.user.name, tweet.text]
      end
    end
    timeline_search_results
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user

	validates :user_id, :body, presence: true

	before_create :post_tweet

	def post_tweet
		user.twitter.update(body)
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	
	def self.create_with_omniauth(auth)
		# binding.pry
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.token = auth['credentials']['token']
      user.secret = auth['credentials']['secret']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

  def twitter
  	@client ||= Twitter::REST::Client.new do |config|
  		config.consumer_key        = Rails.application.secrets.omniauth_provider_key
  		config.consumer_secret     = Rails.application.secrets.omniauth_provider_secret
  		config.access_token        = token
  		config.access_token_secret = secret
		end
		@client
  end

  def display_timeline
  	timeline_search_results = []
  	twitter.home_timeline(options={count: 5}).each do |tweet|
      
  		timeline_search_results << [tweet.attrs[:user][:profile_image_url], tweet.user.name, tweet.text, tweet.created_at]
  	end
  	timeline_search_results
  end

  def reverse_time(hours)
  	timeline_search_results = []
    seconds = hours * 60 * 60
    time = Time.now - seconds
    twitter.home_timeline.each do |tweet|
      if tweet.created_at > time
        timeline_search_results << [tweet.attrs[:user][:profile_image_url], tweet.user.name, tweet.text, tweet.created_at]
      end
    end
    timeline_search_results
  end

  def profile_picture
    twitter.user.attrs[:profile_image_url].gsub("_normal", "")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/backwards_controller.rb
class BackwardsController < ApplicationController

	def new
	  @time = params[:hour].to_i
  	# @timeline = @user.time_travel(@time)
  end

  def show
  	binding.pry
  	@user = User.find(params[:id])
  	@time = params[:hour].to_i
  	@reversed_timeline = @user.reverse_time
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		redirect_to '/auth/twitter'
	end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :set_tweet, only: [:show, :edit, :update, :destroy]

	def index
		@tweet = Tweet.all
	end

	def new
		@tweet = Tweet.new
	end

	def create
		binding.pry
		@tweet = Tweet.new(tweet_params)
		@tweet.user_id = current_user.id
		@tweet.save
		redirect_to user_path(current_user)
	end

	def update
    @tweet.update(tweet_params)
    respond_with(@tweet)
  end

  def destroy
    @tweet.destroy
    respond_with(@tweet)
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

	def tweet_params
		params.require(:tweet).permit(:user_id, :body)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
  	# binding.pry
    @user = current_user
    @timeline = @user.display_timeline

  end

  def update
    # binding.pry
  	@user = User.find(params[:id])
  	@time = params[:hour].to_i
  	@reversed_timeline = @user.reverse_time(@time)
  	@sorted = @reversed_timeline.collect.sort_by{|t| t[2]}

    respond_to do |format|
      format.html {render :_reversed_timeline}
      format.js  
    end
  	
  end


end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Twitter::Autolink
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_navigation.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JetLag</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
<%= render "layouts/navigation" %>
<%= yield %>

</body>
</html>

app/views/tweets/_new.html.erb
<%= form_for Tweet.new do |f| %>
	<%= f.text_area :body %>
	<%= f.submit "Tweet" %>
<% end %>

app/views/users/_reversed_timeline.html.erb
<div>
  <% @sorted.each do |tweet| %>
  	<img src="<%= tweet[0] %>">
    <h3><%= tweet[1] %></h3>
    <p><%= tweet[2] %></p>
    <p><%= tweet[3].strftime("%w %b %y @ %H:%M") %></p>
  <%end%>
</div>

app/views/users/index.html.erb
<h3>List of users:</h3>
<% @users.each do |user| %>

<p><%= user.name %></p>
<% end %>

app/views/users/reversed_timeline.html.erb
	<h3>reversed</h3>
	<% @sorted.each do |tweet| %>
		<p><%= tweet[0] %>: <%= tweet[1] %></p>
	<% end %>

app/views/users/show.html.erb
<img src="<%= @user.profile_picture %>">

<h3>Hello, <%= @user.name %> </h3>

<div>
	<%= render partial: 'tweets/new' %>
</div>

<div id="timeline-results">
	<% @timeline.each do |tweet| %>
		<img src="<%= tweet.first %>">
    <h3><%= tweet.second %></h3>
    <p><%= auto_link(tweet.third).html_safe %></p> 
    <p><%= tweet.fourth.strftime("%w %b %y @ %H:%M") %></p>
  <%end%>
</div>

<div id="hour-form">
	<%= form_tag(user_path, method: "patch", remote: true) do %>
		<%= label_tag(:hour, "Go back:") %>
	  <%= number_field_tag(:hour, placeholder: "Number of Hours") %>
	  <%= submit_tag("Time Travel") %>
	<% end %>
</div>

app/views/users/update.js.erb
$('#timeline-results').html("<%= j render partial: 'reversed_timeline' %>")

app/views/visitors/index.html.erb
<h1>Visitors#index</h1>
<p>Find me in app/views/visitors/index.html.erb</p>